version: "3.3"

services:
  ##################################
  ####        Traefik Proxy Setup           #####
  ###################################
  traefik:
    image: traefik:v2.0
    restart: always
    container_name: traefik
    ports:
      - "80:80"
      - "443:443"
    command:
      - --api.insecure=true
      - --api.dashboard=true
      - --api.debug=true
      - --log.level=DEBUG
      # DEFINE THE NAMES OF YOUR CERT AND KEY IN HERE
      # DEFINE THE REDIRECT RULE IN HERE
      - --providers.file.filename=/config/dynamic.yaml
      - --providers.docker=true
      - --providers.docker.exposedByDefault=false
      - --providers.docker.network=web
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./certs/:/etc/certs/ ## MOUNT THE DIRECTORY WITH YOUR CERTS AND KEYS IN IT
      - ./config/dynamic.yaml:/dynamic.yaml
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.service=api@internal"

  nginx:
    image: nginx:latest
    container_name: nginx
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginx-web.rule=Host(`example.com`)"
      - "traefik.http.routers.nginx-web.entrypoints=web"
      - "traefik.http.routers.nginx-web.middlewares=redirect@file"
      - "traefik.http.routers.nginx-secured.rule=Host(`example.com`)"
      - "traefik.http.routers.nginx-secured.entrypoints=websecure"
      - "traefik.http.routers.nginx-secured.tls=true"

  wordpress:
    container_name: wordpress
    image: wordpress
    depends_on:
      - db
    networks:
      - web
      - backend
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_NAME: exampledb
      WORDPRESS_TABLE_PREFIX: examplepass
    labels:
      ## YOU CAN GET RID OF THESE TOP 3 RULES IF YOUR CONTAINER EXPOSES 443 ##
      - "traefik.http.routers.wordpress.rule=Host(`example2.com`)"
      - "traefik.http.routers.wordpress.entrypoints=web"
      - "traefik.http.routers.wordpress.middlewares=redirect@file"
      - "traefik.http.routers.wordpress-secure.rule=Host(`example2.com`)"
      - "traefik.http.routers.wordpress-secure.entrypoints=websecure"
      - "traefik.http.routers.wordpress-secure.tls=true"
    volumes:
      - ./webroot/:/var/www/html/

  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuse
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: "1"
    volumes:
      - db:/var/lib/mysql
    networks:
      - backend

volumes:
  db: {}

networks:
  web:
    external: true
  backend:
