version: "3.3"

services:
  ################################################
  ####        Traefik Proxy Setup           #####
  ###############################################
  traefik:
    image: traefik:v2.0
    restart: always
    container_name: traefik
    ports:
      - "80:80"
      - "443:443"
    command:
      - --api.insecure=true
      - --api.dashboard=true
      - --api.debug=true
      - --log.level=DEBUG
      - --providers.file.filename=/config/dynamic.yaml
      - --providers.docker=true
        - --providers.docker.exposedByDefault=false
      - --providers.docker.network=web
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./certs/:/etc/certs/
      - ./config/dynamic.yaml:/dynamic.yaml
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.service=api@internal"

  nginx:
    image: nginx:latest
    container_name: nginx
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginx-web.rule=Host(`example.com`)"
      - "traefik.http.routers.nginx-web.entrypoints=web"
      - "traefik.http.routers.nginx-web.middlewares=redirect@file"
      - "traefik.http.routers.nginx-secured.rule=Host(`example.com`)"
      - "traefik.http.routers.nginx-secured.entrypoints=websecure"
      - "traefik.http.routers.nginx-secured.tls=true"

networks:
  web:
    external: true
