tls:
  certificates:
    # THIS REFERENCES CERTS INSIDE THE CONTAINER
    - certFile: /etc/certs/example.crt
      keyFile: /etc/certs/example.key
  options:
    default:
      minVersion: VersionTLS12

# REDIRECT MIDDLEWARE RULE
http:
  middlewares:
    https-redirectscheme:
      redirectScheme:
        scheme: https
